# Generated by Django 4.0.5 on 2022-07-02 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1250)),
                ('url', models.CharField(default='wY6UyatwVTA', max_length=250)),
                ('upload_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('thumbnail', models.CharField(max_length=250)),
            ],
        ),
    ]
